CREATE OR REPLACE VIEW Buscar_Produto AS
SELECT P.ID, P.Descricao, PP.VALOR
FROM PRODUTO P
JOIN PRODUTO_PRECO PP ON P.ID = PP.ID_PRODUTO
WHERE PP.STATUS = 1
WITH CHECK OPTION CONSTRAINT ck_valor_range CHECK (PP.VALOR < 100 OR PP.VALOR > 200);
