CREATE OR REPLACE TRIGGER SALVAR_LOG
AFTER UPDATE ON PRODUTO 
FOR EACH ROW
BEGIN
    INSERT INTO PRODUTO_LOG (ID, CAMPO, VALOR_ANTIGO, NOME_TABELA)
    VALUES(:NEW.ID, 'DESCRICAO', :OLD.DESCRICAO, 'PRODUTO');
    INSERT INTO PRODUTO_LOG (ID, CAMPO, VALOR_ANTIGO, NOME_TABELA)
    VALUES(:NEW.ID, 'STATUS', :OLD.STATUS, 'PRODUTO');
    INSERT INTO PRODUTO_LOG (ID, CAMPO, VALOR_ANTIGO, NOME_TABELA)
    VALUES(:NEW.ID, 'CADASTRO', :OLD.CADASTRO, 'PRODUTO');
    INSERT INTO PRODUTO_LOG (ID, CAMPO, VALOR_ANTIGO, NOME_TABELA)
    VALUES(:NEW.ID, 'QUANTIDADE_EM_ESTOQUE', :OLD.QUANTIDADE_EM_ESTOQUE, 'PRODUTO');
END;

UPDATE PRODUTO
SET DESCRICAO = 'PRODUTO ATUALIZADO',
    STATUS = 'ATIVO',
    CADASTRO = SYSDATE,
    QUANTIDADE_EM_ESTOQUE = 50
WHERE ID = 3;
